### ISSUE TITLE
[SelectionStartDate és SelectionEndDate értelmezése]

### ISSUE THREAD

**Issue by szalaierika** [nav-gov-hu/SAF-T_HU#1]
**SelectionStartDate és SelectionEndDate**

Sziasztok!

Nem értjük a fenti két tag tartalmát, mert a SAFT_HU_Definition.XSD file-ben megadott definíció (Adatszolgáltatással érintett időszak kezdő/befejező dátuma) és a SAFT_HU HANDBOOK HU.pdf 18. oldalán megadott példa, ha PeriodStart, PeriodEnd, PeriodYear tagok tartalmát is, akkor nem konzisztens:

<SelectionStartDate>2020-01-01</SelectionStartDate>
<SelectionEndDate>2020-05-31</SelectionEndDate>
<PeriodStart>1</PeriodStart>
<PeriodEnd>12</PeriodEnd>
<PeriodYear>2020</PeriodYear>

Kérdésünk: a példa rossz vagy az XSD file-ban a fenti tagok definíciója?

Előre is köszönöm!

**Comment by NTCA-tax** [comment]
A példa itt nem túl jó. Napokon belül frissítjük a sémát és a dokumentációt. Jelenleg még az utolsó pontosítások vannak benne, és éppen ezzel a témával a dokumentációban elég részletesen foglalkozunk. Egy kis türelmet kérünk, és remélhetőleg látni fogod, hogyan kellene a teljes szakaszt értelmezni.

**Comment by NTCA-tax** [comment]
Az új dokumentációt feltöltöttük, a példa XML-ek aktualizálásán dolgozunk. A dokumentáció megválaszolta a kérdésedet? Amennyiben igen, akkor zárom az issue-t.

**Comment by szalaierika** [comment]
Igen, köszönöm. Zárhatjuk az issuet.
