### ISSUE TITLE
[DOC] DOC/StandardAccountID.csv számlaszám duplikáció

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/SAF-T_HU#11]
Tisztelt Kollégák!

A 1247, 1248, 1249-es főkönyvi számok duplán szerepelnek a csv-ben. A nevekből ítélve az üzemkörön kívüli ingatlanok esetén ezek elírásra kerültek és 1257, 1258, 1259 lesz a helyes számuk.

1241;Egyéb építmények bruttó értéke;Other structures (gross value)
1247;Egyéb építmények értékhelyesbítése;Value correction of other structures
1248;Egyéb építmények terven felüli értékcsökkenése és visszaírása;Extraordinary depreciation of other structures and written back 
1249;Egyéb építmények terv szerinti értékcskökkenése;Ordinary depreciation of other structures
1251;Üzemkörön kívüli ingatlanok, épületek bruttó értéke ;Properties outside of sphere of operation (gross value)
**_1247_**;Üzemkörön kívüli ingatlanok, épületek értékhelyesbítése;Value correction of properties outside of sphere of operation
**_1248_**;Üzemkörön kívüli ingatlanok, épületek terven felüli értékcsökkenése és visszaírása;Extraordinary depreciation of properties outside of sphere of operation and written back 
**_1249_**;Üzemkörön kívüli ingatlanok, épületek terv szerinti értékcsökkenése;Ordinary depreciation of properties outside of sphere of operation

Kérem a hiba javítását.

Köszönöm!

**Comment by NTCA-tax** [comment]
Köszönjük a jelzést! Javítjuk a CSV-t. Szeptember közepéig egy újabb frissítést fogunk feltölteni, abban már javítjuk.
